management:
  endpoints:
    web:
      exposure:
        include: '*' #路径为 /actuator/sentinel
        #hystrix.stream
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false #刷新时关闭安全验证